---
- name: test aws cli
  hosts: localhost
  gather_facts: no

  tasks:

#    - name: test aws cli
#      shell: aws s3 ls

    - name: show env
      shell: env

    - name: test aws cli
      command: /bin/aws s3 ls
