---
- name: test aws cli
  hosts: all
  gather_facts: no

  tasks:

#    - name: test aws cli
#      shell: aws s3 ls

    - name: show env
      shell: env

    - name: test aws cli
      command: aws s3 ls
      environment:
        PYTHONPATH: "${PYTHONPATH}:/lib/python2.7/site-packages"
