---
- name: test gcp
  hosts: all
  gather_facts: no

  tasks:

    - name: " a image facts"
      gcp_compute_image_facts:
        filters:
          - name = test_object
        state: facts

    - name: test gcloup cmd
      shell: gcloud projects list
