- name: test junos_config
  hosts: junos
  tasks:

    - name: test junos_config
      junos_config:
        lines:
          - delete interfaces ge-0/0/1 unit 0 description "test interface"
          - delete firewall family vpls filter bpdu-guard term allow-ohter then accept
        check_commit: yes
        confirm_commit: yes
