- name: use junos_command module
  hosts: junos
  gather_facts: no

  tasks:

    - name: use junos_command module 
      junos_command:
        command:
          - request message message "test message" user junos
