- name: use junos_command module
  hosts: junos
  gather_facts: no

  tasks:

    - name: use junos_command module 
      junos_command:
        commands:
          - request message message "test message" user junos terminal /dev/pts/0
