- name: set junos banner
  hosts: junos
  tasks:

  - name: junos banner
    junos_banner:
      banner: login
      text: |
        this is my login banner
        that contains a multiline
        string
      state: present
