- name: test junos_config
  hosts: junos
  tasks:

    - name: test junos_config
      junos_config:
        lines:
          - set interfaces ge-0/0/1 unit 0 description "test interface"
          - set firewall family vpls filter bpdu-guard term allow-ohter then accept
          - set interfaces ge-0/0/1 disable
        check_commit: yes
        confirm_commit: yes
        backup: yes
        backup_options:
          dir_path: /var/home/junos
