- name: use junos_command module
  hosts: junos
  gather_facts: no

  vars:
    test_msg: test message

  tasks:

    - name: use junos_command module
      junos_command:
        commands: show system uptime
      register: uptime_result
      when: ansible_network_os == 'junos'

    - name: show variable
      debug:
        msg: "{{ test_msg }}"

    - name: show uptime_result
      debug:
        msg: "{{ uptime_result }}"
